import * as arrayUtils from '../utils/array';

export const home = {
  title: "Hey, it's Sean!",
  body: "I'm a London-based fullstack developer with a background in robotics and microelectronics&ast;. I am a huge fan of innovative thinking and enjoy mixing this way of seeing the world with creativity in a manner which uplifts others. I rise up to life challenges and practice this in juggling hard work with keeping fit and learning new tricks and skills. I'm hacking at all sorts of code in any free time that I get and therefore, together with extensive and broad industry exposure, have developed a valuable understanding of web technologies, the tooling that supports these technologies and the community that have have developed them. Software is more than just the act of writing a piece of code. I view it as the process of understanding a given problem and designing and developing for it a robust and well-performing solution.",
  footnotes: '_&ast; Graduate Mechatronics Engineer (BSc in Engineering in Mechatronics) from the University of Cape Town, South Africa._',
  techSkills: arrayUtils.shuffle([
    {
      title: 'Javascript',
      highlighted: true,
      icon: 'js-square',
      iconSet: 'fab',
      link: 'https://en.wikipedia.org/wiki/JavaScript',
      description: 'A dynamic, untyped programming languaged used across multiple software and engineering industries.',
    },
    {
      title: 'ES6',
      highlighted: false,
      icon: 'js-square',
      iconSet: 'fab',
      link: 'https://kangax.github.io/compat-table/es6/',
      description: 'Short for ECMAScript 6, it is a significant update to the Javascript language, the first since ES5 standardised in 2009.',
    },
    {
      title: 'ES7',
      highlighted: false,
      icon: 'js-square',
      iconSet: 'fab',
      link: 'http://kangax.github.io/compat-table/es2016plus/',
      description: 'Short for ECMAScript 7, this is a small update to the Javascript language since ES6, containing new features such as Object Destructuring and Async functions.',
    },
    {
      title: 'ES8',
      highlighted: false,
      icon: 'js-square',
      iconSet: 'fab',
      link: '',
      description: 'Short for ECMAScript 8, this is a small update to the Javscript language since ES7, containing a few new Object and Array methods and further improvements and support for Async methods.',
    },
    {
      title: 'React',
      highlighted: true,
      icon: 'react',
      iconSet: 'fab',
      link: 'https://reactjs.org/',
      description: 'A Javsacript UI framework developed by Facebook which is advertised to be declarative and component based and enforced great state and structural practices in large applications.',
    },
    {
      title: 'Angular 2',
      highlighted: true,
      icon: 'angular',
      iconSet: 'fab',
      link: 'https://angular.io/',
      description: 'A comprehensive Javascript UI framework which takes advantage of Typescript language features and a strongly integrated compiler to build web components.',
    },
    {
      title: 'Angular 4',
      highlighted: true,
      icon: 'angular',
      iconSet: 'fab',
      link: 'https://angular.io/',
      description: 'An update to the Angular 2 framework.',
    },
    {
      title: 'Google Polymer',
      highlighted: false,
      svg: 'polymer-mono',
      link: 'https://www.polymer-project.org/',
      description: 'A web component framework which leverages the native WebComponent and CustomElement APIs and standards to allow the creation of highly performant HTML components.',
    },
    {
      title: 'Vue',
      highlighted: true,
      icon: 'vuejs',
      iconSet: 'fab',
      link: 'https://vuejs.org/',
      description: 'A progressive component framework which intends to marry core ideas from Angular, Polymer and React whilst keeping the core layer thin and view-centric.',
    },
    {
      title: 'Redux',
      highlighted: true,
      svg: 'redux-mono',
      link: 'https://redux.js.org/',
      description: 'A Javascript state management library, primary built to employ Facebook\'s Flux application architecture, which aims to contain the state of an application allowing it to be used in a predictable manner.',
    },
    {
      title: 'Vuex',
      highlighted: false,
      icon: 'vuejs',
      iconSet: 'fab',
      link: 'https://vuex.vuejs.org/en/intro.html',
      description: 'A state management library, similar to Redux, but built to work around and between Vue web components. It it slightly more flexible in its implementation and more closely represents the Flux application architecture.',
    },
    {
      title: 'Flux',
      highlighted: false,
      svg: 'flux-mono',
      link: 'https://facebook.github.io/flux/',
      description: 'An application architecture developed by Facebook which aims to organise the flow of data in a single loop allowing for predictable state management which scales.',
    },
    {
      title: 'Webpack',
      highlighted: true,
      svg: 'webpack-mono',
      link: 'https://webpack.js.org/',
      description: 'A build tool for web projects which allows for complex and powerful build pipelines to bundle Javascript modules and other assets to be use in the browser.',
    },
    {
      title: 'Rollup',
      highlighted: false,
      textIcon: 'R',
      link: 'https://rollupjs.org/guide/en',
      description: 'A Javascript module bundler known to produce neat and efficient bundles as it aims to work closely with modern moduel standards.',
    },
    {
      title: 'Gulp',
      highlighted: false,
      icon: 'gulp',
      iconSet: 'fab',
      link: 'https://gulpjs.com/',
      description: 'A popular task and build pipeline management tool which sports many third party plugins and developemnt.',
    },
    {
      title: 'Grunt',
      highlighted: false,
      icon: 'grunt',
      iconSet: 'fab',
      link: 'https://gruntjs.com/',
      description: 'A task runner and pipeline management framework similar to Gulp.js.',
    },
    {
      title: 'HTML5',
      highlighted: true,
      icon: 'html5',
      iconSet: 'fab',
      link: 'https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5',
      description: 'The latest standard of the HyperText Markup Language, the layout of the web.',
    },
    {
      title: 'CSS3',
      highlighted: true,
      icon: 'css3-alt',
      iconSet: 'fab',
      link: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS3',
      description: 'The latest production specification of the Cascading Stylesheet language, the style of the web.',
    },
    {
      title: 'SASS',
      highlighted: true,
      icon: 'sass',
      iconSet: 'fab',
      link: 'https://webpack.js.org/',
      description: 'A style language which extends CSS, bringing power language features, functions and modularity to CSS.',
    },
    {
      title: 'Stylus',
      highlighted: false,
      svg: 'stylus-mono',
      link: 'http://stylus-lang.com/',
      description: 'An extension of CSS which sports incredibly relaxed syntax and powerful, functional language features.',
    },
    {
      title: 'PostCSS',
      highlighted: false,
      svg: 'postcss-mono',
      link: 'http://postcss.org/',
      description: 'A CSS preprocessor mostly used to autoprefix written CSS for cross-browser compatibility.',
    },
    {
      title: 'PWA',
      highlighted: false,
      svg: 'pwa-mono',
      link: 'https://developers.google.com/web/progressive-web-apps/',
      description: 'A set of guidelines for developing web applications that perform like native applications across all modern mobile devices and optimise network usage through intelligent caching mechanisms and strategies.',
    },
    {
      title: 'SPA',
      highlighted: false,
      textIcon: 'SPA',
      link: 'https://en.wikipedia.org/wiki/Single-page_application',
      description: 'Standing for Single Page Application, is a web page that contains an entire application, often with multiple views, which is achieved by dynamic, runtime re-rendering of the elements in the DOM.',
    },
    {
      title: 'Browserify',
      highlighted: false,
      svg: 'browserify-mono',
      link: 'http://browserify.org/',
      description: 'A relatively old Javascript module bundler.',
    },
    {
      title: 'Babel',
      highlighted: true,
      svg: 'babel-mono',
      link: 'https://babeljs.io/',
      description: 'A Javascript transpiler allowing developers to use future Javascript features whilst keeping code compatible with current runtimes and browsers.',
    },
    {
      title: 'Typescript',
      highlighted: true,
      svg: 'typescript-mono',
      link: 'https://www.typescriptlang.org/',
      description: 'An extension of Javascript which introduces typed language features as well as some borrowed from C#.',
    },
    {
      title: 'Flow',
      highlighted: false,
      svg: 'flow-mono',
      link: 'https://flow.org/',
      description: 'A library which allows you to annotate Javascript with type definitions, used to perform static type checking during develop-time and compile-time.',
    },
    {
      title: 'RxJs',
      highlighted: false,
      textIcon: 'R',
      link: 'http://reactivex.io/rxjs/',
      description: 'A library for developing reactive data flow in Javascript applications. Angular makes use of RxJs\'s Observables for state management.',
    },
    {
      title: 'Bootstrap',
      highlighted: false,
      svg: 'bootstrap-mono',
      link: 'https://getbootstrap.com/',
      description: 'A popular CSS framework which provides a grid layout system, UI component styling and can integrate with Jquery to allow more complex and dynamic control.',
    },
    {
      title: 'Handlebars',
      highlighted: false,
      svg: 'handlebars-mono',
      link: 'http://handlebarsjs.com/',
      description: 'A static templating framework used to generate HTML from many different templates as well as inject data during compile time.',
    },
    {
      title: 'JQuery',
      highlighted: false,
      svg: 'jquery-mono',
      link: 'https://jquery.com/',
      description: 'Often confused as a language itself, Jquery is an abstraction of the native browser APIs with the aim to make DOM manipulation in Javascript easier.',
    },
    {
      title: 'Contentful',
      highlighted: false,
      svg: 'contentful-mono',
      link: 'https://www.contentful.com/',
      description: 'A modern CMS.',
    },
    {
      title: 'Node.js',
      highlighted: true,
      icon: 'node-js',
      iconSet: 'fab',
      link: 'https://nodejs.org/en/',
      description: 'A Javascipt runtime with an event-driven, single-thread execution model with bindings to native OS libraries.',
    },
    {
      title: 'IBM Loopback',
      highlighted: false,
      svg: 'loopback-mono',
      link: 'https://loopback.io/',
      description: 'A Node.js framework developed by IBM which allows the static declaration of REST models and connection to various data sources which are compiled to Express routes during runtime.',
    },
    {
      title: 'Zendesk',
      highlighted: false,
      svg: 'zendesk-mono',
      link: 'https://www.zendesk.com/',
      description: 'A popular suite of tools for customer support.',
    },
    {
      title: 'Google Maps API',
      highlighted: false,
      svg: 'maps-mono',
      link: 'https://developers.google.com/maps/',
      description: 'A API for the Google Maps Service, provided by Google, for searching for and autocompleting location data.',
    },
    {
      title: 'Yarn',
      highlighted: false,
      svg: 'yarn-mono',
      link: 'https://yarnpkg.com/lang/en/',
      description: 'A Node.js package manager with improved module caching.',
    },
    {
      title: 'NPM',
      highlighted: false,
      icon: 'npm',
      iconSet: 'fab',
      link: 'https://www.npmjs.com/',
      description: 'The package manager built and provided for Node.js with a massive repository of Javascript modules written by the community.',
    },
    {
      title: 'Git',
      highlighted: true,
      svg: 'git-mono',
      link: 'https://git-scm.com/',
      description: 'A version control utility which uses highly performant delta algorithmns to provide fast, multi-context code versioning and collaboration.',
    },
    {
      title: 'Github',
      highlighted: false,
      icon: 'github',
      iconSet: 'fab',
      link: 'https://github.com/',
      description: 'An online code repository built to support Git VCS with additional features for collaborative coding.',
    },
    {
      title: 'Gitlab',
      highlighted: false,
      icon: 'gitlab',
      iconSet: 'fab',
      link: 'https://about.gitlab.com/',
      description: 'An online repository which is similar to Github in its support for projects tracked using Git VCS, but with additional features for in-place CI/CD pipelines and deployment workflows.',
    },
    {
      title: 'Express',
      highlighted: false,
      textIcon: 'EX',
      link: 'https://expressjs.com/',
      description: 'A server framework for Node.js providing web features on top of what Node.js already offers in terms of HTTP.',
    },
    {
      title: 'Koa',
      highlighted: false,
      textIcon: 'K',
      link: 'http://koajs.com/',
      description: 'A server framework for Node.js, similar to Express in principle, which makes use of generator functions as opposed to callback and is smaller and lighter in general.',
    },
    {
      title: 'JWT',
      highlighted: false,
      svg: 'jwt-mono',
      link: 'https://jwt.io/',
      description: 'An open technical standard for digitally signed handshakes in securing a relationship between two end devices or persons.',
    },
    {
      title: 'Material Design',
      highlighted: false,
      svg: 'material-design-mono',
      link: 'https://material.io/guidelines/',
      description: 'A set of guidelines developed by designers at Google for applications that are engaging and interactive on a tactile level as well as robust on al media form factors.',
    },
    {
      title: 'Socket.io',
      highlighted: false,
      svg: 'socket-io-mono',
      link: 'https://socket.io/',
      description: 'A Javascript library which provides an easy to use abstraction of WebSockets for real-time communication with persistence.',
    },
    {
      title: 'WebRTC',
      highlighted: false,
      svg: 'webrtc-mono',
      link: 'https://webrtc.org/',
      description: 'A set of APIs for in-browser realtime communication and media streaming.',
    },
    {
      title: 'GraphQL',
      highlighted: false,
      svg: 'graphql-mono',
      link: 'http://graphql.org/learn/',
      description: 'A powerful query language which allows developers to define types and build queries from those.',
    },
    {
      title: 'ArangoDB',
      highlighted: false,
      svg: 'arangodb-mono',
      link: 'https://www.arangodb.com/',
      description: 'A high-performance, cluster-ready, NoSQL database.',
    },
    {
      title: 'WebWorkers',
      highlighted: false,
      textIcon: 'WW',
      link: 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers',
      description: 'A browser-based means to run Javascript in seperate threads from the main window/page thread.',
    },
    {
      title: 'C + Embedded C',
      highlighted: false,
      textIcon: 'C',
      link: 'https://en.wikipedia.org/wiki/C_(programming_language)',
      description: 'A compiled, typed, low-level langauge used primarily in an embedded context owing to the control over hardware that it gives the developer.',
    },
    {
      title: 'C++',
      highlighted: false,
      svg: 'cpp-mono',
      link: 'https://en.wikipedia.org/wiki/C%2B%2B',
      description: 'An object-oriented programming language which extends C and provides a better platform on which to develop complex desktop applications, however, remains suitable for some embedded use cases.',
    },
    {
      title: 'NW.js',
      highlighted: false,
      textIcon: 'NW',
      link: 'https://nwjs.io/',
      description: 'An application platform similar to Electron able to run web and Node.js projects as desktop applications.',
    },
    {
      title: 'Electron',
      highlighted: true,
      svg: 'electron-mono',
      link: 'https://electronjs.org/',
      description: 'A web application container built using Node.js and Chromium for running web projects as desktop applications across all desktop platforms.',
    },
    {
      title: 'RTOS',
      highlighted: false,
      textIcon: 'RTOS',
      link: 'https://en.wikipedia.org/wiki/Real-time_operating_system',
      description: 'An operating system which deals with IO in realtime, often with the aid of multiple threads and most commonly a significant OS topology when used for embedded applications.',
    },
  ]),
};
